# Generated by Django 4.2.18 on 2025-01-21 18:15

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                validators=[content.validators.validate_pdf],
            ),
        ),
    ]
